version: "3.7"
services:
  app:
    volumes:
      - ./:/var/www
    build:
      context: .
    depends_on:
      - db
    tty: true
    networks:
      - laravel
    ports:
      - "8000:8000"
    environment:
      PORT: ${PORT}
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      LOG_CHANNEL: ${LOG_CHANNEL}
      LOG_DEPRECATIONS_CHANNEL: ${LOG_DEPRECATIONS_CHANNEL}
      LOG_LEVEL: ${LOG_LEVEL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER}
      CACHE_DRIVER: ${CACHE_DRIVER}
      FILESYSTEM_DISK: ${FILESYSTEM_DISK}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION}
      SESSION_DRIVER: ${SESSION_DRIVER}
      SESSION_LIFETIME: ${SESSION_LIFETIME}
      MEMCACHED_HOST: ${MEMCACHED_HOST}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_USE_PATH_STYLE_ENDPOINT: ${AWS_USE_PATH_STYLE_ENDPOINT}
      PUSHER_APP_ID: ${PUSHER_APP_ID}
      PUSHER_APP_KEY: ${PUSHER_APP_KEY}
      PUSHER_APP_SECRET: ${PUSHER_APP_SECRET}
      PUSHER_HOST: ${PUSHER_HOST}
      PUSHER_PORT: ${PUSHER_PORT}
      PUSHER_SCHEME: ${PUSHER_SCHEME}
      PUSHER_APP_CLUSTER: ${PUSHER_APP_CLUSTER}
      VITE_APP_NAME: ${VITE_APP_NAME}
      VITE_PUSHER_APP_KEY: ${VITE_PUSHER_APP_KEY}
      VITE_PUSHER_HOST: ${VITE_PUSHER_HOST}
      VITE_PUSHER_PORT: ${VITE_PUSHER_PORT}
      VITE_PUSHER_SCHEME: ${VITE_PUSHER_SCHEME}
      VITE_PUSHER_APP_CLUSTER: ${VITE_PUSHER_APP_CLUSTER}
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: unless-stopped
    tty: true
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/
    networks:
      - laravel
  db:
    image: mysql:8.0.2
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    restart: always
    networks:
      - laravel

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: phpmyadmin
  #   environment:
  #     - PMA_ARBITRARY=1
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - laravel
networks:
  laravel:
    driver: bridge
volumes:
  mysql-data:
