version: "3.7"
services:
    app:
        build: .
        container_name: php
        ports:
            - "5133:5133"
            - "8000:8000"
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - app-network
    db:
        image: mysql:8.0.2
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - ${DB_PORT}:3306
        volumes:
            - mysql-data:/var/lib/mysql
            - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        restart: always
        networks:
            - app-network
    # nginx:
    #     image: nginx:latest
    #     volumes:
    #         - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    #         - ./:/var/www
    #     ports:
    #         - "80:80"
    #     networks:
    #         - app-network
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     container_name: phpmyadmin
    #     environment:
    #         - PMA_ARBITRARY=1
    #     ports:
    #         - "8080:80"
    #     depends_on:
    #         - db

volumes:
    mysql-data:
networks:
    vite-php-setup:
    app-network:
        driver: bridge
